import { CanvasSettings } from '../types/project';
import { Layer } from '../types/layer';

export interface ProjectTemplate {
  id: string;
  name: string;
  category: 'promo' | 'social' | 'titles' | 'quotes' | 'tech' | 'branding';
  description: string;
  thumbnailGradient: string;
  canvas: CanvasSettings;
  layers: Layer[];
}

export const PROJECT_TEMPLATES: ProjectTemplate[] = [
  {
    id: 'kinetic-typography-bold',
    name: 'Kinetic Typography Promo',
    category: 'promo',
    description: 'High energy kinetic pop with vibrant gradient glow',
    thumbnailGradient: 'from-indigo-600 via-purple-600 to-pink-500',
    canvas: {
      width: 1920,
      height: 1080,
      fps: 30,
      duration: 5.0,
      backgroundColor: '#090a0f',
      aspectRatio: '16:9',
      preset: '1080p',
    },
    layers: [
      {
        id: 'bg-pill-1',
        name: 'Accent Pill Glow',
        type: 'shape',
        visible: true,
        locked: false,
        startTime: 0.1,
        endTime: 4.8,
        trackIndex: 0,
        transform: {
          x: 960,
          y: 540,
          width: 820,
          height: 220,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#151824',
          stroke: '#6366f1',
          strokeWidth: 2,
          opacity: 0.85,
          blur: 0,
          shadowColor: 'rgba(99, 102, 241, 0.4)',
          shadowBlur: 30,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'shape_elastic_pop',
          inDuration: 0.8,
          inStagger: 0,
          loopPreset: 'loop_breathing_pulse',
          loopSpeed: 1,
          loopIntensity: 1,
          outPreset: 'text_out_elastic_shrink',
          outDuration: 0.5,
        },
        shape: {
          shapeType: 'pill',
          cornerRadius: 110,
          closed: true,
        },
      },
      {
        id: 'text-main-title',
        name: 'MOCEAN.IO',
        type: 'text',
        visible: true,
        locked: false,
        startTime: 0.3,
        endTime: 4.8,
        trackIndex: 1,
        transform: {
          x: 960,
          y: 510,
          width: 800,
          height: 140,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#ffffff',
          gradient: {
            type: 'linear',
            angle: 90,
            stops: [
              { offset: 0, color: '#ffffff' },
              { offset: 0.5, color: '#00f2fe' },
              { offset: 1, color: '#4facfe' },
            ],
          },
          stroke: '',
          strokeWidth: 0,
          opacity: 1,
          blur: 0,
          shadowColor: 'rgba(0, 242, 254, 0.5)',
          shadowBlur: 25,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'text_letter_bounce',
          inDuration: 0.9,
          inStagger: 0.05,
          loopPreset: 'loop_neon_glow_pulse',
          loopSpeed: 1,
          loopIntensity: 1,
          outPreset: 'text_out_fade_down',
          outDuration: 0.5,
        },
        text: {
          text: 'MOTION IN SECONDS',
          fontFamily: 'Lato',
          fontSize: 68,
          fontWeight: '900',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 4,
          lineHeight: 1.1,
          textTransform: 'uppercase',
          staggerUnit: 'character',
        },
      },
      {
        id: 'text-sub-title',
        name: 'Subtitle Callout',
        type: 'text',
        visible: true,
        locked: false,
        startTime: 0.8,
        endTime: 4.8,
        trackIndex: 2,
        transform: {
          x: 960,
          y: 585,
          width: 600,
          height: 40,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#94a3b8',
          stroke: '',
          strokeWidth: 0,
          opacity: 1,
          blur: 0,
          shadowColor: 'transparent',
          shadowBlur: 0,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'text_word_stagger_up',
          inDuration: 0.7,
          inStagger: 0.1,
          outPreset: 'text_out_fade_down',
          outDuration: 0.5,
          loopSpeed: 1,
          loopIntensity: 1,
        },
        text: {
          text: 'Zero Keyframe Stress • Instant 4K Export',
          fontFamily: 'Space Grotesk',
          fontSize: 24,
          fontWeight: '600',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 3,
          lineHeight: 1.2,
          textTransform: 'uppercase',
          staggerUnit: 'word',
        },
      },
    ],
  },
  {
    id: 'cyber-glitch-hook',
    name: 'Cyber Glitch Title',
    category: 'titles',
    description: 'Futuristic glitch text with neon cyan and pink split glow',
    thumbnailGradient: 'from-cyan-500 via-pink-500 to-purple-800',
    canvas: {
      width: 1920,
      height: 1080,
      fps: 30,
      duration: 4.0,
      backgroundColor: '#05060a',
      aspectRatio: '16:9',
      preset: '1080p',
    },
    layers: [
      {
        id: 'cyber-star-1',
        name: 'Cyber Star Accent',
        type: 'shape',
        visible: true,
        locked: false,
        startTime: 0.2,
        endTime: 3.8,
        trackIndex: 0,
        transform: {
          x: 960,
          y: 420,
          width: 90,
          height: 90,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#00f2fe',
          stroke: '#ff007f',
          strokeWidth: 3,
          opacity: 1,
          blur: 0,
          shadowColor: '#00f2fe',
          shadowBlur: 35,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'shape_spin_bloom',
          inDuration: 0.8,
          inStagger: 0,
          loopPreset: 'loop_floating_hover',
          loopSpeed: 1.2,
          loopIntensity: 1,
          outPreset: 'text_out_elastic_shrink',
          outDuration: 0.4,
        },
        shape: {
          shapeType: 'star',
          cornerRadius: 0,
          points: 4,
          innerRadiusRatio: 0.35,
          closed: true,
        },
      },
      {
        id: 'cyber-text-headline',
        name: 'Cyber Title',
        type: 'text',
        visible: true,
        locked: false,
        startTime: 0.3,
        endTime: 3.8,
        trackIndex: 1,
        transform: {
          x: 960,
          y: 540,
          width: 900,
          height: 130,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#00f2fe',
          stroke: '#ff007f',
          strokeWidth: 2,
          opacity: 1,
          blur: 0,
          shadowColor: '#ff007f',
          shadowBlur: 30,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'text_glitch_reveal',
          inDuration: 0.7,
          inStagger: 0.03,
          loopPreset: 'loop_neon_glow_pulse',
          loopSpeed: 2,
          loopIntensity: 1,
          outPreset: 'text_out_glitch_vanish',
          outDuration: 0.4,
        },
        text: {
          text: 'CYBER ARCHITECTURE',
          fontFamily: 'JetBrains Mono',
          fontSize: 72,
          fontWeight: '900',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 6,
          lineHeight: 1.1,
          textTransform: 'uppercase',
          staggerUnit: 'character',
        },
      },
    ],
  },
  {
    id: 'tiktok-reels-vertical',
    name: '9:16 Social Reel Hook',
    category: 'social',
    description: 'Designed specifically for viral vertical TikTok / Reels / Shorts',
    thumbnailGradient: 'from-amber-400 via-rose-500 to-indigo-600',
    canvas: {
      width: 1080,
      height: 1920,
      fps: 30,
      duration: 5.0,
      backgroundColor: '#0a0a14',
      aspectRatio: '9:16',
      preset: '1080p_Vertical',
    },
    layers: [
      {
        id: 'reel-tag-bg',
        name: 'Hook Badge',
        type: 'shape',
        visible: true,
        locked: false,
        startTime: 0.1,
        endTime: 4.8,
        trackIndex: 0,
        transform: {
          x: 540,
          y: 720,
          width: 320,
          height: 64,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#ff007f',
          stroke: '#ffffff',
          strokeWidth: 2,
          opacity: 1,
          blur: 0,
          shadowColor: 'rgba(255, 0, 127, 0.6)',
          shadowBlur: 20,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'shape_elastic_pop',
          inDuration: 0.6,
          inStagger: 0,
          outPreset: 'text_out_elastic_shrink',
          outDuration: 0.4,
          loopSpeed: 1,
          loopIntensity: 1,
        },
        shape: {
          shapeType: 'pill',
          cornerRadius: 32,
          closed: true,
        },
      },
      {
        id: 'reel-tag-text',
        name: 'Tag Label',
        type: 'text',
        visible: true,
        locked: false,
        startTime: 0.2,
        endTime: 4.8,
        trackIndex: 1,
        transform: {
          x: 540,
          y: 720,
          width: 300,
          height: 40,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#ffffff',
          stroke: '',
          strokeWidth: 0,
          opacity: 1,
          blur: 0,
          shadowColor: 'transparent',
          shadowBlur: 0,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'text_kinetic_pop',
          inDuration: 0.5,
          inStagger: 0.02,
          outPreset: 'text_out_fade_down',
          outDuration: 0.4,
          loopSpeed: 1,
          loopIntensity: 1,
        },
        text: {
          text: '🔥 TRENDING NOW',
          fontFamily: 'Inter',
          fontSize: 22,
          fontWeight: '800',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 2,
          lineHeight: 1,
          textTransform: 'uppercase',
          staggerUnit: 'character',
        },
      },
      {
        id: 'reel-main-text',
        name: 'Main Hook Question',
        type: 'text',
        visible: true,
        locked: false,
        startTime: 0.4,
        endTime: 4.8,
        trackIndex: 2,
        transform: {
          x: 540,
          y: 920,
          width: 900,
          height: 240,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#ffffff',
          stroke: '#000000',
          strokeWidth: 4,
          opacity: 1,
          blur: 0,
          shadowColor: 'rgba(0,0,0,0.8)',
          shadowBlur: 20,
          shadowOffsetX: 0,
          shadowOffsetY: 8,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'text_word_stagger_up',
          inDuration: 0.8,
          inStagger: 0.15,
          loopPreset: 'loop_breathing_pulse',
          loopSpeed: 1.5,
          loopIntensity: 1,
          outPreset: 'text_out_fade_down',
          outDuration: 0.5,
        },
        text: {
          text: 'HOW TO ANIMATE\nANYTHING IN SECONDS',
          fontFamily: 'Bebas Neue',
          fontSize: 88,
          fontWeight: '900',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 3,
          lineHeight: 1.15,
          textTransform: 'uppercase',
          staggerUnit: 'word',
        },
      },
    ],
  },
  {
    id: 'editorial-minimal-quote',
    name: 'Minimalist Editorial Reveal',
    category: 'quotes',
    description: 'Elegant serif typography with smooth cinematic blur-in',
    thumbnailGradient: 'from-stone-700 via-stone-900 to-black',
    canvas: {
      width: 1920,
      height: 1080,
      fps: 30,
      duration: 6.0,
      backgroundColor: '#0c0d12',
      aspectRatio: '16:9',
      preset: '1080p',
    },
    layers: [
      {
        id: 'quote-body',
        name: 'Quote Text',
        type: 'text',
        visible: true,
        locked: false,
        startTime: 0.3,
        endTime: 5.7,
        trackIndex: 0,
        transform: {
          x: 960,
          y: 500,
          width: 1200,
          height: 160,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#f8fafc',
          stroke: '',
          strokeWidth: 0,
          opacity: 1,
          blur: 0,
          shadowColor: 'transparent',
          shadowBlur: 0,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'text_blur_flare_in',
          inDuration: 1.2,
          inStagger: 0.08,
          loopPreset: 'loop_floating_hover',
          loopSpeed: 0.6,
          loopIntensity: 0.6,
          outPreset: 'text_out_blur_disperse',
          outDuration: 0.8,
        },
        text: {
          text: '“Design is intelligence made visible.”',
          fontFamily: 'Playfair Display',
          fontSize: 64,
          fontWeight: '600',
          fontStyle: 'italic',
          textAlign: 'center',
          letterSpacing: 2,
          lineHeight: 1.3,
          textTransform: 'none',
          staggerUnit: 'word',
        },
      },
      {
        id: 'quote-author',
        name: 'Author Name',
        type: 'text',
        visible: true,
        locked: false,
        startTime: 1.2,
        endTime: 5.7,
        trackIndex: 1,
        transform: {
          x: 960,
          y: 600,
          width: 600,
          height: 40,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#a855f7',
          stroke: '',
          strokeWidth: 0,
          opacity: 1,
          blur: 0,
          shadowColor: 'rgba(168, 85, 247, 0.4)',
          shadowBlur: 15,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'text_smooth_fade_slide',
          inDuration: 0.8,
          inStagger: 0.03,
          outPreset: 'text_out_fade_down',
          outDuration: 0.6,
          loopSpeed: 1,
          loopIntensity: 1,
        },
        text: {
          text: '— ALINA WHEELER',
          fontFamily: 'Lato',
          fontSize: 22,
          fontWeight: '700',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 6,
          lineHeight: 1,
          textTransform: 'uppercase',
          staggerUnit: 'character',
        },
      },
    ],
  },
  {
    id: 'youtube-lower-third',
    name: 'Modern YouTube Lower Third',
    category: 'titles',
    description: 'Sleek stream/video lower third with glass card & animated name',
    thumbnailGradient: 'from-blue-600 via-indigo-600 to-cyan-500',
    canvas: {
      width: 1920,
      height: 1080,
      fps: 30,
      duration: 5.0,
      backgroundColor: '#0c0d12',
      aspectRatio: '16:9',
      preset: '1080p',
    },
    layers: [
      {
        id: 'lt-card',
        name: 'Lower Third Card',
        type: 'shape',
        visible: true,
        locked: false,
        startTime: 0.2,
        endTime: 4.8,
        trackIndex: 0,
        transform: {
          x: 480,
          y: 860,
          width: 580,
          height: 110,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#151824',
          stroke: '#6366f1',
          strokeWidth: 2,
          opacity: 0.9,
          blur: 0,
          shadowColor: 'rgba(99, 102, 241, 0.4)',
          shadowBlur: 20,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'shape_elastic_pop',
          inDuration: 0.6,
          inStagger: 0,
          outPreset: 'text_out_elastic_shrink',
          outDuration: 0.4,
          loopSpeed: 1,
          loopIntensity: 1,
        },
        shape: {
          shapeType: 'rectangle',
          cornerRadius: 16,
          closed: true,
        },
      },
      {
        id: 'lt-name',
        name: 'Creator Name',
        type: 'text',
        visible: true,
        locked: false,
        startTime: 0.4,
        endTime: 4.8,
        trackIndex: 1,
        transform: {
          x: 480,
          y: 840,
          width: 520,
          height: 40,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#ffffff',
          stroke: '',
          strokeWidth: 0,
          opacity: 1,
          blur: 0,
          shadowColor: 'transparent',
          shadowBlur: 0,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'text_kinetic_pop',
          inDuration: 0.6,
          inStagger: 0.03,
          outPreset: 'text_out_fade_down',
          outDuration: 0.4,
          loopSpeed: 1,
          loopIntensity: 1,
        },
        text: {
          text: 'ALEX RIVERA',
          fontFamily: 'Montserrat',
          fontSize: 34,
          fontWeight: '900',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 3,
          lineHeight: 1,
          textTransform: 'uppercase',
          staggerUnit: 'character',
        },
      },
      {
        id: 'lt-sub',
        name: 'Channel Tag',
        type: 'text',
        visible: true,
        locked: false,
        startTime: 0.7,
        endTime: 4.8,
        trackIndex: 2,
        transform: {
          x: 480,
          y: 885,
          width: 520,
          height: 24,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#00f2fe',
          stroke: '',
          strokeWidth: 0,
          opacity: 1,
          blur: 0,
          shadowColor: 'transparent',
          shadowBlur: 0,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'text_word_stagger_up',
          inDuration: 0.5,
          inStagger: 0.05,
          outPreset: 'text_out_fade_down',
          outDuration: 0.4,
          loopSpeed: 1,
          loopIntensity: 1,
        },
        text: {
          text: 'Creative Motion Director • @alexrivera',
          fontFamily: 'Lato',
          fontSize: 16,
          fontWeight: '700',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 2,
          lineHeight: 1,
          textTransform: 'none',
          staggerUnit: 'word',
        },
      },
    ],
  },
  {
    id: 'synthwave-retro-grid',
    name: '80s Synthwave Neon Title',
    category: 'titles',
    description: 'Vibrant retro outrun glow title with pink & cyan electric sheen',
    thumbnailGradient: 'from-pink-600 via-purple-700 to-cyan-500',
    canvas: {
      width: 1920,
      height: 1080,
      fps: 30,
      duration: 5.0,
      backgroundColor: '#080512',
      aspectRatio: '16:9',
      preset: '1080p',
    },
    layers: [
      {
        id: 'sw-sun',
        name: 'Neon Sun Disc',
        type: 'shape',
        visible: true,
        locked: false,
        startTime: 0.1,
        endTime: 4.8,
        trackIndex: 0,
        transform: {
          x: 960,
          y: 460,
          width: 320,
          height: 320,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#ff007f',
          gradient: {
            type: 'linear',
            angle: 0,
            stops: [
              { offset: 0, color: '#ffea00' },
              { offset: 0.6, color: '#ff007f' },
              { offset: 1, color: '#7928ca' },
            ],
          },
          stroke: '#ff007f',
          strokeWidth: 2,
          opacity: 0.9,
          blur: 0,
          shadowColor: 'rgba(255, 0, 127, 0.6)',
          shadowBlur: 40,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'shape_elastic_pop',
          inDuration: 0.8,
          inStagger: 0,
          loopPreset: 'loop_neon_glow_pulse',
          loopSpeed: 1.5,
          loopIntensity: 1,
          outPreset: 'text_out_elastic_shrink',
          outDuration: 0.4,
        },
        shape: {
          shapeType: 'circle',
          cornerRadius: 0,
          closed: true,
        },
      },
      {
        id: 'sw-title',
        name: 'Synth Title',
        type: 'text',
        visible: true,
        locked: false,
        startTime: 0.3,
        endTime: 4.8,
        trackIndex: 1,
        transform: {
          x: 960,
          y: 560,
          width: 900,
          height: 120,
          scaleX: 1,
          scaleY: 1,
          rotation: -4,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#00f2fe',
          stroke: '#ffffff',
          strokeWidth: 2,
          opacity: 1,
          blur: 0,
          shadowColor: '#00f2fe',
          shadowBlur: 30,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'text_letter_bounce',
          inDuration: 0.9,
          inStagger: 0.04,
          loopPreset: 'loop_floating_hover',
          loopSpeed: 1,
          loopIntensity: 1,
          outPreset: 'text_out_glitch_vanish',
          outDuration: 0.4,
        },
        text: {
          text: 'NEON HORIZON',
          fontFamily: 'Righteous',
          fontSize: 78,
          fontWeight: '900',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 6,
          lineHeight: 1,
          textTransform: 'uppercase',
          staggerUnit: 'character',
        },
      },
    ],
  },
  {
    id: 'podcast-audio-hook',
    name: 'Podcast Waveform Hook',
    category: 'social',
    description: 'Dynamic talk audio clip teaser with kinetic quote subtitles',
    thumbnailGradient: 'from-violet-600 to-indigo-900',
    canvas: {
      width: 1080,
      height: 1920,
      fps: 30,
      duration: 6.0,
      backgroundColor: '#0a0a14',
      aspectRatio: '9:16',
      preset: '1080p_Vertical',
    },
    layers: [
      {
        id: 'pod-badge',
        name: 'Speaker Label',
        type: 'shape',
        visible: true,
        locked: false,
        startTime: 0.1,
        endTime: 5.8,
        trackIndex: 0,
        transform: {
          x: 540,
          y: 750,
          width: 380,
          height: 60,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#1e1b4b',
          stroke: '#818cf8',
          strokeWidth: 2,
          opacity: 1,
          blur: 0,
          shadowColor: 'rgba(129, 140, 248, 0.4)',
          shadowBlur: 20,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'shape_elastic_pop',
          inDuration: 0.6,
          inStagger: 0,
          outPreset: 'text_out_elastic_shrink',
          outDuration: 0.4,
          loopSpeed: 1,
          loopIntensity: 1,
        },
        shape: {
          shapeType: 'pill',
          cornerRadius: 30,
          closed: true,
        },
      },
      {
        id: 'pod-speaker',
        name: 'Speaker Text',
        type: 'text',
        visible: true,
        locked: false,
        startTime: 0.2,
        endTime: 5.8,
        trackIndex: 1,
        transform: {
          x: 540,
          y: 750,
          width: 360,
          height: 36,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#ffffff',
          stroke: '',
          strokeWidth: 0,
          opacity: 1,
          blur: 0,
          shadowColor: 'transparent',
          shadowBlur: 0,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'text_kinetic_pop',
          inDuration: 0.5,
          inStagger: 0.03,
          outPreset: 'text_out_fade_down',
          outDuration: 0.4,
          loopSpeed: 1,
          loopIntensity: 1,
        },
        text: {
          text: '🎙️ EPISODE 42 • FOUNDERS',
          fontFamily: 'Lato',
          fontSize: 20,
          fontWeight: '900',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 2,
          lineHeight: 1,
          textTransform: 'uppercase',
          staggerUnit: 'character',
        },
      },
      {
        id: 'pod-quote',
        name: 'Kinetic Quote Words',
        type: 'text',
        visible: true,
        locked: false,
        startTime: 0.5,
        endTime: 5.8,
        trackIndex: 2,
        transform: {
          x: 540,
          y: 980,
          width: 880,
          height: 320,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#facc15',
          stroke: '#000000',
          strokeWidth: 3,
          opacity: 1,
          blur: 0,
          shadowColor: 'rgba(0,0,0,0.8)',
          shadowBlur: 20,
          shadowOffsetX: 0,
          shadowOffsetY: 8,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'text_word_stagger_up',
          inDuration: 0.8,
          inStagger: 0.15,
          loopPreset: 'loop_breathing_pulse',
          loopSpeed: 1.2,
          loopIntensity: 1,
          outPreset: 'text_out_fade_down',
          outDuration: 0.5,
        },
        text: {
          text: '“THE MOMENT YOU STOP\nWAITING FOR PERMISSION,\nEVERYTHING CHANGES.”',
          fontFamily: 'Anton',
          fontSize: 66,
          fontWeight: '900',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 3,
          lineHeight: 1.25,
          textTransform: 'uppercase',
          staggerUnit: 'word',
        },
      },
    ],
  },
  {
    id: 'breaking-news-alert',
    name: 'Breaking News Alert Header',
    category: 'promo',
    description: 'Urgent broadcast header with flashing alert badge and ticker title',
    thumbnailGradient: 'from-red-600 via-rose-700 to-slate-900',
    canvas: {
      width: 1920,
      height: 1080,
      fps: 30,
      duration: 5.0,
      backgroundColor: '#090a10',
      aspectRatio: '16:9',
      preset: '1080p',
    },
    layers: [
      {
        id: 'news-pill',
        name: 'Alert Badge',
        type: 'shape',
        visible: true,
        locked: false,
        startTime: 0.1,
        endTime: 4.8,
        trackIndex: 0,
        transform: {
          x: 960,
          y: 430,
          width: 360,
          height: 60,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#dc2626',
          stroke: '#ffffff',
          strokeWidth: 2,
          opacity: 1,
          blur: 0,
          shadowColor: 'rgba(220, 38, 38, 0.7)',
          shadowBlur: 30,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'shape_elastic_pop',
          inDuration: 0.6,
          inStagger: 0,
          loopPreset: 'loop_shake_vibe',
          loopSpeed: 1,
          loopIntensity: 1,
          outPreset: 'text_out_elastic_shrink',
          outDuration: 0.4,
        },
        shape: {
          shapeType: 'pill',
          cornerRadius: 30,
          closed: true,
        },
      },
      {
        id: 'news-badge-txt',
        name: 'Badge Text',
        type: 'text',
        visible: true,
        locked: false,
        startTime: 0.2,
        endTime: 4.8,
        trackIndex: 1,
        transform: {
          x: 960,
          y: 430,
          width: 340,
          height: 36,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#ffffff',
          stroke: '',
          strokeWidth: 0,
          opacity: 1,
          blur: 0,
          shadowColor: 'transparent',
          shadowBlur: 0,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'text_kinetic_pop',
          inDuration: 0.4,
          inStagger: 0.02,
          outPreset: 'text_out_fade_down',
          outDuration: 0.4,
          loopSpeed: 1,
          loopIntensity: 1,
        },
        text: {
          text: '🚨 SPECIAL ANNOUNCEMENT',
          fontFamily: 'Lato',
          fontSize: 20,
          fontWeight: '900',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 2,
          lineHeight: 1,
          textTransform: 'uppercase',
          staggerUnit: 'character',
        },
      },
      {
        id: 'news-headline',
        name: 'Main Headline',
        type: 'text',
        visible: true,
        locked: false,
        startTime: 0.4,
        endTime: 4.8,
        trackIndex: 2,
        transform: {
          x: 960,
          y: 560,
          width: 1200,
          height: 120,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#ffffff',
          stroke: '#000000',
          strokeWidth: 2,
          opacity: 1,
          blur: 0,
          shadowColor: 'rgba(0,0,0,0.7)',
          shadowBlur: 20,
          shadowOffsetX: 0,
          shadowOffsetY: 6,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'text_word_stagger_up',
          inDuration: 0.7,
          inStagger: 0.1,
          outPreset: 'text_out_fade_down',
          outDuration: 0.5,
          loopSpeed: 1,
          loopIntensity: 1,
        },
        text: {
          text: 'NEXT GENERATION MOTION GRAPHICS\nAVAILABLE EVERYWHERE TODAY',
          fontFamily: 'Montserrat',
          fontSize: 52,
          fontWeight: '900',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 2,
          lineHeight: 1.15,
          textTransform: 'uppercase',
          staggerUnit: 'word',
        },
      },
    ],
  },
];
