import { CanvasSettings } from '../types/project';
import { Layer } from '../types/layer';

export interface ProjectTemplate {
  id: string;
  name: string;
  category: 'promo' | 'social' | 'titles' | 'quotes' | 'tech';
  description: string;
  thumbnailGradient: string;
  canvas: CanvasSettings;
  layers: Layer[];
}

export const PROJECT_TEMPLATES: ProjectTemplate[] = [
  {
    id: 'kinetic-typography-bold',
    name: 'Kinetic Typography Promo',
    category: 'promo',
    description: 'High energy kinetic pop with vibrant gradient glow',
    thumbnailGradient: 'from-indigo-600 via-purple-600 to-pink-500',
    canvas: {
      width: 1920,
      height: 1080,
      fps: 30,
      duration: 5.0,
      backgroundColor: '#090a0f',
      aspectRatio: '16:9',
      preset: '1080p',
    },
    layers: [
      {
        id: 'bg-pill-1',
        name: 'Accent Pill Glow',
        type: 'shape',
        visible: true,
        locked: false,
        startTime: 0.1,
        endTime: 4.8,
        trackIndex: 0,
        transform: {
          x: 960,
          y: 540,
          width: 820,
          height: 220,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#151824',
          stroke: '#6366f1',
          strokeWidth: 2,
          opacity: 0.85,
          blur: 0,
          shadowColor: 'rgba(99, 102, 241, 0.4)',
          shadowBlur: 30,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'shape_elastic_pop',
          inDuration: 0.8,
          inStagger: 0,
          loopPreset: 'loop_breathing_pulse',
          loopSpeed: 1,
          loopIntensity: 1,
          outPreset: 'text_out_elastic_shrink',
          outDuration: 0.5,
        },
        shape: {
          shapeType: 'pill',
          cornerRadius: 110,
          closed: true,
        },
      },
      {
        id: 'text-main-title',
        name: 'MOCEAN.IO',
        type: 'text',
        visible: true,
        locked: false,
        startTime: 0.3,
        endTime: 4.8,
        trackIndex: 1,
        transform: {
          x: 960,
          y: 510,
          width: 800,
          height: 140,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#ffffff',
          gradient: {
            type: 'linear',
            angle: 90,
            stops: [
              { offset: 0, color: '#ffffff' },
              { offset: 0.5, color: '#00f2fe' },
              { offset: 1, color: '#4facfe' },
            ],
          },
          stroke: '',
          strokeWidth: 0,
          opacity: 1,
          blur: 0,
          shadowColor: 'rgba(0, 242, 254, 0.5)',
          shadowBlur: 25,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'text_letter_bounce',
          inDuration: 0.9,
          inStagger: 0.05,
          loopPreset: 'loop_neon_glow_pulse',
          loopSpeed: 1,
          loopIntensity: 1,
          outPreset: 'text_out_fade_down',
          outDuration: 0.5,
        },
        text: {
          text: 'MOTION IN SECONDS',
          fontFamily: 'Montserrat',
          fontSize: 68,
          fontWeight: '900',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 4,
          lineHeight: 1.1,
          textTransform: 'uppercase',
          staggerUnit: 'character',
        },
      },
      {
        id: 'text-sub-title',
        name: 'Subtitle Callout',
        type: 'text',
        visible: true,
        locked: false,
        startTime: 0.8,
        endTime: 4.8,
        trackIndex: 2,
        transform: {
          x: 960,
          y: 585,
          width: 600,
          height: 40,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#94a3b8',
          stroke: '',
          strokeWidth: 0,
          opacity: 1,
          blur: 0,
          shadowColor: 'transparent',
          shadowBlur: 0,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'text_word_stagger_up',
          inDuration: 0.7,
          inStagger: 0.1,
          outPreset: 'text_out_fade_down',
          outDuration: 0.5,
          loopSpeed: 1,
          loopIntensity: 1,
        },
        text: {
          text: 'Zero Keyframe Stress • Instant 4K Export',
          fontFamily: 'Space Grotesk',
          fontSize: 24,
          fontWeight: '600',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 3,
          lineHeight: 1.2,
          textTransform: 'uppercase',
          staggerUnit: 'word',
        },
      },
    ],
  },
  {
    id: 'cyber-glitch-hook',
    name: 'Cyber Glitch Title',
    category: 'titles',
    description: 'Futuristic glitch text with neon cyan and pink split glow',
    thumbnailGradient: 'from-cyan-500 via-pink-500 to-purple-800',
    canvas: {
      width: 1920,
      height: 1080,
      fps: 30,
      duration: 4.0,
      backgroundColor: '#05060a',
      aspectRatio: '16:9',
      preset: '1080p',
    },
    layers: [
      {
        id: 'cyber-star-1',
        name: 'Cyber Star Accent',
        type: 'shape',
        visible: true,
        locked: false,
        startTime: 0.2,
        endTime: 3.8,
        trackIndex: 0,
        transform: {
          x: 960,
          y: 420,
          width: 90,
          height: 90,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#00f2fe',
          stroke: '#ff007f',
          strokeWidth: 3,
          opacity: 1,
          blur: 0,
          shadowColor: '#00f2fe',
          shadowBlur: 35,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'shape_spin_bloom',
          inDuration: 0.8,
          inStagger: 0,
          loopPreset: 'loop_floating_hover',
          loopSpeed: 1.2,
          loopIntensity: 1,
          outPreset: 'text_out_elastic_shrink',
          outDuration: 0.4,
        },
        shape: {
          shapeType: 'star',
          cornerRadius: 0,
          points: 4,
          innerRadiusRatio: 0.35,
          closed: true,
        },
      },
      {
        id: 'cyber-text-headline',
        name: 'Cyber Title',
        type: 'text',
        visible: true,
        locked: false,
        startTime: 0.3,
        endTime: 3.8,
        trackIndex: 1,
        transform: {
          x: 960,
          y: 540,
          width: 900,
          height: 130,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#00f2fe',
          stroke: '#ff007f',
          strokeWidth: 2,
          opacity: 1,
          blur: 0,
          shadowColor: '#ff007f',
          shadowBlur: 30,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'text_glitch_reveal',
          inDuration: 0.7,
          inStagger: 0.03,
          loopPreset: 'loop_neon_glow_pulse',
          loopSpeed: 2,
          loopIntensity: 1,
          outPreset: 'text_out_glitch_vanish',
          outDuration: 0.4,
        },
        text: {
          text: 'CYBER ARCHITECTURE',
          fontFamily: 'JetBrains Mono',
          fontSize: 72,
          fontWeight: '900',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 6,
          lineHeight: 1.1,
          textTransform: 'uppercase',
          staggerUnit: 'character',
        },
      },
    ],
  },
  {
    id: 'tiktok-reels-vertical',
    name: '9:16 Social Reel Hook',
    category: 'social',
    description: 'Designed specifically for viral vertical TikTok / Reels / Shorts',
    thumbnailGradient: 'from-amber-400 via-rose-500 to-indigo-600',
    canvas: {
      width: 1080,
      height: 1920,
      fps: 30,
      duration: 5.0,
      backgroundColor: '#0a0a14',
      aspectRatio: '9:16',
      preset: '1080p_Vertical',
    },
    layers: [
      {
        id: 'reel-tag-bg',
        name: 'Hook Badge',
        type: 'shape',
        visible: true,
        locked: false,
        startTime: 0.1,
        endTime: 4.8,
        trackIndex: 0,
        transform: {
          x: 540,
          y: 720,
          width: 320,
          height: 64,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#ff007f',
          stroke: '#ffffff',
          strokeWidth: 2,
          opacity: 1,
          blur: 0,
          shadowColor: 'rgba(255, 0, 127, 0.6)',
          shadowBlur: 20,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'shape_elastic_pop',
          inDuration: 0.6,
          inStagger: 0,
          outPreset: 'text_out_elastic_shrink',
          outDuration: 0.4,
          loopSpeed: 1,
          loopIntensity: 1,
        },
        shape: {
          shapeType: 'pill',
          cornerRadius: 32,
          closed: true,
        },
      },
      {
        id: 'reel-tag-text',
        name: 'Tag Label',
        type: 'text',
        visible: true,
        locked: false,
        startTime: 0.2,
        endTime: 4.8,
        trackIndex: 1,
        transform: {
          x: 540,
          y: 720,
          width: 300,
          height: 40,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#ffffff',
          stroke: '',
          strokeWidth: 0,
          opacity: 1,
          blur: 0,
          shadowColor: 'transparent',
          shadowBlur: 0,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'text_kinetic_pop',
          inDuration: 0.5,
          inStagger: 0.02,
          outPreset: 'text_out_fade_down',
          outDuration: 0.4,
          loopSpeed: 1,
          loopIntensity: 1,
        },
        text: {
          text: '🔥 TRENDING NOW',
          fontFamily: 'Inter',
          fontSize: 22,
          fontWeight: '800',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 2,
          lineHeight: 1,
          textTransform: 'uppercase',
          staggerUnit: 'character',
        },
      },
      {
        id: 'reel-main-text',
        name: 'Main Hook Question',
        type: 'text',
        visible: true,
        locked: false,
        startTime: 0.4,
        endTime: 4.8,
        trackIndex: 2,
        transform: {
          x: 540,
          y: 920,
          width: 900,
          height: 240,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#ffffff',
          stroke: '#000000',
          strokeWidth: 4,
          opacity: 1,
          blur: 0,
          shadowColor: 'rgba(0,0,0,0.8)',
          shadowBlur: 20,
          shadowOffsetX: 0,
          shadowOffsetY: 8,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'text_word_stagger_up',
          inDuration: 0.8,
          inStagger: 0.15,
          loopPreset: 'loop_breathing_pulse',
          loopSpeed: 1.5,
          loopIntensity: 1,
          outPreset: 'text_out_fade_down',
          outDuration: 0.5,
        },
        text: {
          text: 'HOW TO ANIMATE\nANYTHING IN SECONDS',
          fontFamily: 'Bebas Neue',
          fontSize: 88,
          fontWeight: '900',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 3,
          lineHeight: 1.15,
          textTransform: 'uppercase',
          staggerUnit: 'word',
        },
      },
    ],
  },
  {
    id: 'editorial-minimal-quote',
    name: 'Minimalist Editorial Reveal',
    category: 'quotes',
    description: 'Elegant serif typography with smooth cinematic blur-in',
    thumbnailGradient: 'from-stone-700 via-stone-900 to-black',
    canvas: {
      width: 1920,
      height: 1080,
      fps: 30,
      duration: 6.0,
      backgroundColor: '#0c0d12',
      aspectRatio: '16:9',
      preset: '1080p',
    },
    layers: [
      {
        id: 'quote-body',
        name: 'Quote Text',
        type: 'text',
        visible: true,
        locked: false,
        startTime: 0.3,
        endTime: 5.7,
        trackIndex: 0,
        transform: {
          x: 960,
          y: 500,
          width: 1200,
          height: 160,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#f8fafc',
          stroke: '',
          strokeWidth: 0,
          opacity: 1,
          blur: 0,
          shadowColor: 'transparent',
          shadowBlur: 0,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'text_blur_flare_in',
          inDuration: 1.2,
          inStagger: 0.08,
          loopPreset: 'loop_floating_hover',
          loopSpeed: 0.6,
          loopIntensity: 0.6,
          outPreset: 'text_out_blur_disperse',
          outDuration: 0.8,
        },
        text: {
          text: '“Design is intelligence made visible.”',
          fontFamily: 'Playfair Display',
          fontSize: 64,
          fontWeight: '600',
          fontStyle: 'italic',
          textAlign: 'center',
          letterSpacing: 2,
          lineHeight: 1.3,
          textTransform: 'none',
          staggerUnit: 'word',
        },
      },
      {
        id: 'quote-author',
        name: 'Author Name',
        type: 'text',
        visible: true,
        locked: false,
        startTime: 1.2,
        endTime: 5.7,
        trackIndex: 1,
        transform: {
          x: 960,
          y: 600,
          width: 600,
          height: 40,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          anchorX: 0.5,
          anchorY: 0.5,
        },
        style: {
          fill: '#a855f7',
          stroke: '',
          strokeWidth: 0,
          opacity: 1,
          blur: 0,
          shadowColor: 'rgba(168, 85, 247, 0.4)',
          shadowBlur: 15,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          blendMode: 'source-over',
        },
        animations: {
          inPreset: 'text_smooth_fade_slide',
          inDuration: 0.8,
          inStagger: 0.03,
          outPreset: 'text_out_fade_down',
          outDuration: 0.6,
          loopSpeed: 1,
          loopIntensity: 1,
        },
        text: {
          text: '— ALINA WHEELER',
          fontFamily: 'Inter',
          fontSize: 22,
          fontWeight: '700',
          fontStyle: 'normal',
          textAlign: 'center',
          letterSpacing: 6,
          lineHeight: 1,
          textTransform: 'uppercase',
          staggerUnit: 'character',
        },
      },
    ],
  },
];
