import { MotionPresetConfig } from '../types/animation';

export const MOTION_PRESETS: Record<string, MotionPresetConfig> = {
  // --- ENTRANCE (IN) PRESETS ---
  text_kinetic_pop: {
    id: 'text_kinetic_pop',
    name: 'Kinetic Pop',
    category: 'in',
    description: 'Dynamic overshoot scale pop with upward momentum',
    duration: 0.6,
    staggerDelay: 0.03,
    easing: 'springSnappy',
  },
  text_typewriter: {
    id: 'text_typewriter',
    name: 'Typewriter Cursor',
    category: 'in',
    description: 'Crisp character-by-character appearance with blinking cursor feel',
    duration: 1.2,
    staggerDelay: 0.05,
    easing: 'linear',
  },
  text_word_stagger_up: {
    id: 'text_word_stagger_up',
    name: 'Word Stagger Rise',
    category: 'in',
    description: 'Modern editorial slide up with smooth easing per word',
    duration: 0.8,
    staggerDelay: 0.12,
    easing: 'easeOutExpo',
  },
  text_letter_bounce: {
    id: 'text_letter_bounce',
    name: 'Letter Spring Bounce',
    category: 'in',
    description: 'Playful bouncy elastic drop for each character',
    duration: 0.9,
    staggerDelay: 0.04,
    easing: 'springWobbly',
  },
  text_blur_flare_in: {
    id: 'text_blur_flare_in',
    name: 'Cinematic Blur In',
    category: 'in',
    description: 'High-end film title reveal from depth blur to sharp focus',
    duration: 0.8,
    staggerDelay: 0.03,
    easing: 'easeOutCubic',
  },
  text_glitch_reveal: {
    id: 'text_glitch_reveal',
    name: 'Cyber Glitch Reveal',
    category: 'in',
    description: 'High-energy digital flicker and horizontal offset slices',
    duration: 0.6,
    staggerDelay: 0.02,
    easing: 'easeInOutQuad',
  },
  text_flip_drop: {
    id: 'text_flip_drop',
    name: '3D Flip Drop',
    category: 'in',
    description: '3D perspective tumble and settle with depth shadow',
    duration: 0.75,
    staggerDelay: 0.04,
    easing: 'easeOutBack',
  },
  text_mask_wipe_left: {
    id: 'text_mask_wipe_left',
    name: 'Horizontal Mask Wipe',
    category: 'in',
    description: 'Smooth wipe transition from left to right',
    duration: 0.7,
    staggerDelay: 0.02,
    easing: 'easeInOutCubic',
  },
  text_mask_wipe_up: {
    id: 'text_mask_wipe_up',
    name: 'Vertical Mask Slide',
    category: 'in',
    description: 'Sleek bottom-to-top masked emergence',
    duration: 0.7,
    staggerDelay: 0.03,
    easing: 'easeOutExpo',
  },
  text_elastic_zoom: {
    id: 'text_elastic_zoom',
    name: 'Elastic Zoom Boom',
    category: 'in',
    description: 'Impactful zoom from 2.5x scale with elastic rubber settling',
    duration: 0.85,
    staggerDelay: 0.04,
    easing: 'easeOutElastic',
  },
  text_smooth_fade_slide: {
    id: 'text_smooth_fade_slide',
    name: 'Smooth Silk Slide',
    category: 'in',
    description: 'Ultra clean modern UI slide & fade',
    duration: 0.6,
    staggerDelay: 0.02,
    easing: 'easeOutQuad',
  },

  // --- CONTINUOUS (LOOP) PRESETS ---
  loop_breathing_pulse: {
    id: 'loop_breathing_pulse',
    name: 'Breathing Pulse',
    category: 'loop',
    description: 'Gentle organic scale rhythmic expansion and contraction',
    duration: 2.0,
    easing: 'easeInOutQuad',
  },
  loop_neon_glow_pulse: {
    id: 'loop_neon_glow_pulse',
    name: 'Neon Glow Pulse',
    category: 'loop',
    description: 'Vibrant pulsing glow shadow and slight luminance shift',
    duration: 1.5,
    easing: 'easeInOutCubic',
  },
  loop_floating_hover: {
    id: 'loop_floating_hover',
    name: 'Floating Hover',
    category: 'loop',
    description: 'Smooth anti-gravity vertical float and subtle tilt',
    duration: 2.5,
    easing: 'easeInOutSine' as any,
  },
  loop_kinetic_wave: {
    id: 'loop_kinetic_wave',
    name: 'Kinetic Letter Wave',
    category: 'loop',
    description: 'Continuous sinusoidal wave ripple across characters',
    duration: 1.8,
    easing: 'easeInOutQuad',
  },
  loop_shake_vibe: {
    id: 'loop_shake_vibe',
    name: 'Energetic Vibrate',
    category: 'loop',
    description: 'High tempo micro-jitter and kinetic tension',
    duration: 0.4,
    easing: 'linear',
  },
  loop_gradient_shimmer: {
    id: 'loop_gradient_shimmer',
    name: 'Gradient Shimmer',
    category: 'loop',
    description: 'Moving sheen light sweep across surfaces',
    duration: 2.0,
    easing: 'easeInOutCubic',
  },

  // --- EXIT (OUT) PRESETS ---
  text_out_fade_down: {
    id: 'text_out_fade_down',
    name: 'Sink & Fade Out',
    category: 'out',
    description: 'Downward momentum smooth exit',
    duration: 0.5,
    staggerDelay: 0.02,
    easing: 'easeInQuad',
  },
  text_out_blur_disperse: {
    id: 'text_out_blur_disperse',
    name: 'Vaporize Blur Out',
    category: 'out',
    description: 'Expands into blurred particles and dissolves',
    duration: 0.6,
    staggerDelay: 0.03,
    easing: 'easeInExpo',
  },
  text_out_elastic_shrink: {
    id: 'text_out_elastic_shrink',
    name: 'Elastic Shrink',
    category: 'out',
    description: 'Anticipation stretch followed by rapid shrink away',
    duration: 0.55,
    staggerDelay: 0.02,
    easing: 'easeInBack',
  },
  text_out_glitch_vanish: {
    id: 'text_out_glitch_vanish',
    name: 'Glitch Vanish',
    category: 'out',
    description: 'Instant digital cut and glitch offset exit',
    duration: 0.4,
    staggerDelay: 0.01,
    easing: 'linear',
  },
  text_out_mask_wipe: {
    id: 'text_out_mask_wipe',
    name: 'Mask Wipe Away',
    category: 'out',
    description: 'Clean sliding mask wipe disappear',
    duration: 0.5,
    staggerDelay: 0.02,
    easing: 'easeInOutQuad',
  },

  // --- SHAPE & IMAGE PRESETS ---
  shape_elastic_pop: {
    id: 'shape_elastic_pop',
    name: 'Elastic Shape Pop',
    category: 'in',
    description: 'Punchy elastic scale for shapes & badges',
    duration: 0.7,
    easing: 'springSnappy',
  },
  shape_spin_bloom: {
    id: 'shape_spin_bloom',
    name: 'Spin & Bloom',
    category: 'in',
    description: '180-degree rotation bloom with scale burst',
    duration: 0.8,
    easing: 'easeOutBack',
  },
  shape_dash_draw: {
    id: 'shape_dash_draw',
    name: 'Neon Line Draw',
    category: 'in',
    description: 'Animated stroke offset outline draw',
    duration: 1.0,
    easing: 'easeInOutCubic',
  },
  image_ken_burns: {
    id: 'image_ken_burns',
    name: 'Ken Burns Pan & Zoom',
    category: 'loop',
    description: 'Smooth slow cinematic zoom and subtle pan',
    duration: 6.0,
    easing: 'linear',
  },
  image_drop_bounce: {
    id: 'image_drop_bounce',
    name: 'Polaroid Drop Bounce',
    category: 'in',
    description: 'Gravity drop with realistic rotational rebound',
    duration: 0.85,
    easing: 'easeOutBounce',
  },
  image_parallax_tilt: {
    id: 'image_parallax_tilt',
    name: 'Parallax Tilt In',
    category: 'in',
    description: 'Perspective angled entry with dynamic scale',
    duration: 0.8,
    easing: 'easeOutExpo',
  },
};

export const PRESET_CATEGORIES = [
  { id: 'in', name: 'Entrances (In)', description: 'Eye-catching layer reveals' },
  { id: 'loop', name: 'Continuous (Loop)', description: 'Subtle motion loops & breathing effects' },
  { id: 'out', name: 'Exits (Out)', description: 'Clean, cinematic departures' },
] as const;
